# -*- coding: utf-8 -*-
"""minkowskiDistance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cRjnRJ7PFYg_kQVGEgXJuxR8TEuniNvU
"""

!pip install matplotlib

from pylab import *


def minknowskiDist(v1, v2, p):
    dist = 0.0
    for i in range(len(v1)):
        dist += abs(v1[i] - v2[i]) **p

    return dist**(1/p)

class Animal(object):
    def __init__ (self, name, featuers):
        self.name = name
        self.features = pylab.array(featuers)

    def getName(self):
        return self.name

    def getFeatures(self):
        return self.features

    def distance(self, other):
        return minknowskiDist(self.getFeatures(), other.getFeatures(), 2)

def compareAnimals(animals, precision):
    columnLabels = []

    for a in animals:
        columnLabels.append(a.getName())

    rowLabels = columnLabels[:]
    tableVals = []


    for a1 in animals:
        row = []

        for a2 in animals:
            if a1 == a2:
                row.append('--')
            else:
                distance = a1.distance(a2)
                row.append(str(round(distance, precision)))

        tableVals.append(row)

    table = pylab.table(rowLabels = rowLabels,
                        colLabels = columnLabels,
                        cellText = tableVals,
                        cellLoc = 'center',
                        loc = 'center',
                        colWidths = [0.2]*len(animals))

    table.scale(1, 2.5)
    pylab.savefig('distances')

rattlesnake = Animal('rattlesnake', [1,1,1,1,0])
boa = Animal('boa\nconstrictor', [0,1,0,1,0])
dartFrog = Animal('dart frog', [1,0,1,0,4])
animals = [rattlesnake, boa, dartFrog]
compareAnimals(animals, 3)

alligator = Animal('alligator', [1,1,0,1,4])
animals.append(alligator)

compareAnimals(animals, 3)